---
- name: Copying qemu static
  become: true
  copy:
    src: /usr/bin/qemu-arm-static
    dest: ./part2/usr/bin/qemu-arm-static
    mode: 0755
    owner: root
    group: root

- name: Update cache of apt
  raw: apt-get update
  delegate_to: ./part2

- name: Upgrade packages
  raw: apt-get -y upgrade
  delegate_to: ./part2

- name: Add vim nocp for pi user
  lineinfile:
    path: /home/pi/.vimrc
    owner: pi
    group: pi
    create: yes
    mode: 0644
    state: present
    line: "set nocompatible"
  delegate_to: ./part2

- name: create symbolic link for root for .vimrc
  file:
    src: "/home/pi/.vimrc"
    dest: "/root/.vimrc"
    state: link
  delegate_to: ./part2

