- hosts: raspbian
  vars_files: 
    - pass.yaml
    - config.yaml
  vars:
    needreboot: false
  become: yes
  roles:
#    - initial
#    - develop
#    - dragino
#    - gps
    - finishing
#    - finalreboot   
