- hosts: raspbian
  vars_files: 
    - pass.yaml
  become: yes
  tasks:
#    - name: Update cache of apt
#      apt:
#        update_cache: yes
#        cache_valid_time: 3600

#    - name: Upgrade packages
#      apt:
#        name: "*"
#        state: latest

    - name: installing packages
      apt: 
        name: 
          - gpsd 
          - gpsd-clients
          - python-gps 
     
    - name: Copying gpsd
      copy:
        src: gpsd
        dest: /etc/default
        mode: 0644

    - name: Restart gpsd
      service:
        name: gpsd
        sleep: 5
        state: restarted
    

#    - name: change default password
    
