---
- name: installing packages
  apt: 
    name: 
      - pulseaudio
      - pulseaudio-module-bluetooth
      - pi-bluetooth
  delegate_to: ./part2

# Check that hci0 is ok. (For integrated hciuart.service )
# Check that bluetoothd started
# Pulseaudio start manual
# TURN OFF interated Wifi if using integrated bluetooth or use dongles

- name: configuring /boot/config.txt
  lineinfile:
    path: ./part1/config.txt
    line: "{{ item }}"
    state: present
  with_items:
    - dtparam=spi=on
    - dtoverlay=pi3-disable-bt-overlay
    - core_freq=250
    - enable_uart=1
    - force_turbo=1

- name: Adding user to group lp (Printer group)
  user:
    name: pi
    append: yes
    groups: lp
  delegate_to: ./part2

- name: Naming bluetooth Device
  lineinfile:
    path: /etc/machine-info
    create: yes
    mode: 0644
    owner: root
    group: root
    state: present
    regexp: '^PRETTY_HOSTNAME'
    line: "PRETTY_HOSTNAME = Kolonka"
  delegate_to: ./part2

- name: Adding configuring bluetooth to auto-start
  lineinfile:
    path: /etc/rc.local
    state: present
    regexp: "{{ item }}"
    line: "{{ item }}"
    insertbefore: '^exit 0'
  with_items:
    - ip link set dev wlan0 down
    - pulseaudio -D
    - sleep 1
    - hciconfig hci0 class 0x200420
  delegate_to: ./part2

- name: Configuring Pulse
  lineinfile:
    path: /etc/pulse/daemon.conf
    state: present
    regexp: '^{{ item.split("=")[0] }}='
    line: "{{ item }}"
  with_items:
    - resample-method = ffmpeg
    - ; resample-method = trivial
    - enable-remixing = no
    - enable-lfe-remixing = no
    - default-sample-format = s32le
    - default-sample-rate = 192000
    - alternate-sample-rate = 176000
    - default-sample-channels = 2
    - exit-idle-time = -1
  delegate_to: ./part2

#Default Pulse Audio Settings at
#/usr/share/alsa/init/default
#Saved with 'alsactl store' settings:
#/var/lib/alsa/asound.state

#Pulseaudio should be runned
#- name: Adjusting Volume
#  command: {{ item }}
#  with_items:
#  - amixer -q set Master 100%
#  - pactl set-sink-volume 0 100%
#  delegate_to: ./part2


# Air Play
#- name: Configuring AirPlay
#  lineinfile:
#    create: yes
#    path: /etc/shairport-sync.conf
#    state: present
#    regexp: '^{{ item }}'
#    line: "{{ item }}"
#  with_items:
#    - '// General Settings'
#    - 'general = {'
#    - '   name = "${NAME}";'
#    - '   volume_range_db = 40;'
#    - '};'
#  delegate_to: ./part2

