---
- name: Update cache of apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    name: "*"
    state: latest

- name: Add vim nocp
  lineinfile:
    path: /home/pi/.vimrc
    owner: pi
    group: pi
    create: yes
    mode: 0644
    state: present
    line: "set nocompatible"
