---
- name: Install wiringpi
  apt:
    name:
      - wiringpi
      - gpsd
      - gpsd-clients
      - python-gps    
  delegate_to: ./part2

- name: configuring /boot/config.txt
  lineinfile:
    path: ./part1/config.txt
    line: "{{ item }}"
    state: present
  with_items:
    - dtparam=spi=on
    - dtoverlay=pi3-disable-bt-overlay
    - core_freq=250
    - enable_uart=1
    - force_turbo=1

- name: Copying gpsd for Lora Dragino Hat
  copy:
    src: gpsd
    dest: /etc/default
    mode: 0644
  delegate_to: ./part2

#- name: Restart gpsd
#  service:
#    name: gpsd
#    state: restarted

#- name: Check GPS
#  raw: 'until cat /dev/ttyS0 | grep -m 1 "GPRMC"; do : ; done'
#  register: output2

