---
- name: installing packages
  apt: 
    name: 
      - gpsd 
      - gpsd-clients
      - python-gps 
     
- name: Copying gpsd for USB stick
  copy:
    src: gpsd
    dest: /etc/default
    mode: 0644

- name: Restart gpsd
  service:
    name: gpsd
    state: restarted

- name: Check GPS
  raw: 'until cat /dev/ttyACM0 | grep -m 1 "GNGLL"; do : ; done'
  register: output2
    
- name: print output GPS
  debug: msg="{{ output2.stdout_lines }}"

