---
- name: Configuring routing for server
  lineinfile:
    path: /etc/sysctl.conf
    state: present
    line: "net.ipv4.ip_forward=1"
    regexp: 'net\.ipv4\.ip_forward=1'
  delegate_to: ./part2

- name: Copying nat iptables save file for masquerade through eth0
  copy:
    src: iptables.ipv4.nat
    dest: /etc/iptables.ipv4.nat
    owner: root
    group: root
    mode: 0644
  delegate_to: ./part2

- name: Adding load iptables nat rules at boot
  lineinfile:
    path: /etc/rc.local
    state: present
    line: "iptables-restore < /etc/iptables.ipv4.nat"
    insertbefore: '^exit 0'
  delegate_to: ./part2

